### ISSUE TITLE
Approach to version compatibility (brainstorming)

### ISSUE THREAD

**Issue by keithlayne** [localstack/aws-cdk#3]
It's really great to see this project released.  Thanks to everyone who has worked on it.

I'm a little concerned though about maintaining compatibility with the base CDK libraries.  The `package.json` has CDK dependencies at `0.0.0`, which I assume gets handled by the tooling, but `npm info aws-cdk-local` shows:

```
dependencies:
@aws-cdk/cloud-assembly-schema: 1.54.0                     
@aws-cdk/cloudformation-diff: 1.54.0                        
@aws-cdk/cx-api: 1.54.0                   
@aws-cdk/region-info: 1.54.0   
```

...which is not terrific if you're using a different version of the CDK in your project.  It's not the end of the world to duplicate some dependencies, but this doesn't seem ideal.

In general IMO this is a kinda hard problem - the CDK repo is large.  Also, they release weekly (IIRC) and minor versions are potentially breaking.  I'm not sure how much of the affected package is prone to change, and all the packages *and* their CDK dependencies (I think) get version-bumped in lock step regardless of what's changed.

One strategy could be to rebase on each release, fix any breaks, and publish a compatible version.  This seems tiring.  Because of no semver you can't set a reasonable constraint that will work with future CDK releases with confidence that this package won't break.  Also, the big monorepo means you have to fork the entire thing just to tweak one package, which is not ideal.

It would be great if this project could somehow isolate the single package it changes and have peer dependencies on the CDK packages, but because of no semver that's not foolproof either, and it would be challenging to keep up with upstream changes.  

Is this meant to run alongside `aws-cdk` or completely replace it?  If it replaces the CDK version than potentially it could live as a versioned patch that could be applied with `patch-package` or yarn 2.  

I'm not thrilled with anything I've written here but would love to get anyone else's thoughts.

**Comment by keithlayne** [comment]
It was also mentioned in a thread that a CDK plugin could be useful.  I have no idea if that's feasible at this point.

**Comment by whummer** [comment]
Hi @keithlayne , many thanks for sharing your thoughts. I fully agree with the points you've raised here. In fact, we just ran into this issue today when trying to push a small change and rebasing the fork onto latest upstream `master`. Keeping the code bases in sync will be really tiresome in the long run.

There are several open discussion threads and open PRs in the upstream repo, e.g.:
https://github.com/aws/aws-cdk/issues/1989
https://github.com/aws/aws-cdk/pull/7337
https://github.com/aws/aws-cdk/pull/9179

I think (hope) that the required functionality (i.e., setting individual endpoints) will be added upstream soon, then this fork will become obsolete and we can create a small wrapper that simply configures the required `localhost` endpoints and uses the underlying CDK version that the user has configured locally.

What are your thoughts? Any feedback, as well as any help getting the upstream changes merged would be much appreciated!

**Comment by keithlayne** [comment]
Thanks for the response - I'm watching those issues as well. I'd love to see a good integration merged upstream.  I agree that some kind of wrapper that does as little as possible would be perfect.

My experience with getting changes merged into the CDK repo has not been positive.  Outside contributions just seem to be a very low priority in general.  I can't imagine something like this even being on their radar as far as priority.  That gives me mixed feelings on this whole effort - I'm thrilled that you have something working but I can't rely on the upstream maintainers to care if they break it.

**Comment by whummer** [comment]
Hi @keithlayne . Quick update - we were now able to release a first version of the thin wrapper script that we discussed above. This repo is now deprecated - can you please give it a try with the new implementation here: https://github.com/localstack/aws-cdk-local Hope that the new version works for you - please keep us posted how it goes. Thanks!

**Comment by keithlayne** [comment]
👍  That's outstanding. I think this approach will probably be a lot better for everyone involved.  I'll try to give it a spin soon.
