### ISSUE TITLE
Cannot set the enpoint to something other than localhost

### ISSUE THREAD

**Issue by mattsoftware** [localstack/aws-cdk#5]
I run localstack in my local environment using docker-compose. To be able to run the cdk against my localstack environment, i need to set the endpoint to http://localstack, instead of localhost. I would love to be able to override the endpoint to better suit my local environment.

Thanks.

**Comment by whummer** [comment]
Thanks for reporting @mattsoftware . Please note that this repo is now deprecated - can you please give it a try with the new implementation here (see Configuration section in the README): https://github.com/localstack/aws-cdk-local Hope that helps - please open a follow-up ticket in the new repo if the problem persists. Thanks!
